### PR TITLE
Ensemble corrector: bugfix by retracing our steps

### PR DESCRIPTION
**Pull request by lmcarboneau**
This version is working!  I can continue checking some of the other optimizations, but I'm currently seeing ensemble corrections taking ~0.36 seconds on my laptop - if we're looking for more speed in the future this might be a good target but the logic is stubbornly delicate

### CODE REVIEW

**Comment by lmcarboneau** [comment]
Also I guess a reasonable TODO going forward is to make that code coverage number go up 😅

**Comment by rhandberg** [comment]
Just did a major update, which reverts many of the change that passed the tests with FFI targets.

**Comment by rhandberg** [comment]
Once this PR is merged, I will add the new testing-framework to the devel branch, which should also help significantly with the code coverage.

**Comment by rhandberg** [comment]
Everything now runs through and checks out, with only minor changes to the output compared with the original version. I am merging now.

**Pull request merged**
